PRODUCT_PROPERTY_OVERRIDES +=  \
    debug.stagefright.ccodec=0 \
    drm.service.enabled=true \
    media.mediadrmservice.enable=true \
    persist.sys.zram_enabled=1 \
    ro.apex.updatable=true \
    ro.carrier=unknown \
    ro.config.alarm_alert=Alarm_Classic.ogg \
    ro.config.notification_sound=OnTheHunt.ogg \
    ro.control_privapp_permissions=enforce \
    ro.crypto.volume.filenames_mode=aes-256-cts \
    ro.hardware.power=ranchu \
    vendor.rild.libpath=/vendor/lib64/libgoldfish-ril.so \
